spring:
  datasource:
    url: jdbc:h2:file:C:\Users\multicampus\Desktop\Project_ALDY\DB\h2db
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
  h2:
    console:
      enabled: true

logging.level:
  org.hibernate.SQL: debug

# swaggerdoc
springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: 'true'
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
